### ISSUE TITLE
Using icon examples instead of #

### ISSUE THREAD

**Issue by marioortizmanero** [polybar/polybar-scripts#163]
I would like to discuss about using icons by default instead of `#`. We should look for the most used font to display icons (for example FontAwesome) and use them by default. 

As they are the most used ones, most of the times the user won't even have to customize the script, which can be a bit tedious if the used icons aren't stored in a variable at the top of the script, meaning that you have to dig through it to find the command that prints the icons and change them. Looking for icons can be a bit tedious too, since some fonts have over 1500.

Maybe we could add a disclaimer saying that the icons used by default are from FontAwesome, but that they can be changed inside the script.

What do you think?

**Comment by x70b1** [comment]
The question is what's the benefit of that. Currently the benefit is that in the script is visible where an icon is. If a `#` appears on your bar, you know: Something has to be modified. 

For you, FontAwesome is the default. Someone else might say something completely different. But the point is: I don't care. Everybody can do what they like. So here is my easy rule for this. Icons are replaced by `#`. That works well so far.

There are some exceptions, like the weather scripts. But that's because I built a function for the icon mapping which is very icon specific.

I don't want to edit pull requests here, because someone thinks another icon would fit better.

If you cannot edit a text file, you should not use `polybar`. You use it because it's easy to customize, not because it looks good out of the box.

**Comment by marioortizmanero** [comment]
Yes you are totally right. My point was that if we used the most common icons, which probably are FontAwesome or Noto Color Emoji, it'd save most people the time it takes to dig them. Or maybe adding a section in the skeleton that suggests common icons for said script? But yeah it might be unnecessary.

**Comment by x70b1** [comment]
The problem is not to suggest some icons. The problem is to maintain that suggestions. That would lead to a lot of work. We have over 70 scripts here. Would you like to change all suggestions if there is a new version of a font? For example FontAwesome 4 to FontAwesome 5? Hell no. 

If someone comes here and grabs a script, he can also replace his icons for himself.

But you find a lot of suggestions on reddit/unixporn. :sunglasses:
