### ISSUE TITLE
Pllayer-mpris-tail blacklist option not working for chromium.

### ISSUE THREAD

**Issue by Gobln** [polybar/polybar-scripts#169]
Hi, I posted on r/polybar about this issue, and someone confirmed they couldn't see a workaround either and suggested I open an issue.

I'm trying to blacklist chromium from displaying youtube and other web video titles onto the bar, as I don't really want that information displayed since I only need the script for music player information. I've tried both -b and --blacklist in the exec command string, but the as per a comment on my reddit post, the bus name is `org.mpris.MediaPlayer2.chromium.instanceXXXX` with the x's being a different number each time. Any advice on how to block the entire app would be great.

**Comment by x70b1** [comment]
@Cybolic - any comments?

**Comment by Rapiz1** [comment]
Change Line 55 `return bus_name.startswith('org.mpris.MediaPlayer2') and bus_name.split('.')[-1] not in self.blacklist` to `        return bus_name.startswith('org.mpris.MediaPlayer2') and bus_name.split('.')[3] not in self.blacklist` should solve it.
Yes, just change one digit.
(And invoke with the argument -b chromium)

**Comment by Gobln** [comment]
@Rapiz1 that appears to have fixed the issue as far as I can tell, so your help is greatly appreciated. If an outside can make recommendations, I would strongly consider adding this fix somewhere in the docs as I imagine many other people will have the same need.

**Comment by daltroaugusto** [comment]
I know this is already closed (since 2 years), but I think this can be an useful update for Chromium's bug situation. Ya, that bug is still present, but I found a "workaround" for those who want MediaSession to work just for some websites. I just wrote a tiny userscript with the following content:

```
// ==UserScript==
// @name        Force disable MediaSession
// @namespace   Violentmonkey Scripts
// @match       *://*/*
// @excepts     *://*deezer.com/*
// @grant       none
// @version     1.0
// @author      Daltro Augusto <daltro.campanher@acad.ufsm.br>
// @description 19/03/2021 20:23:23
// ==/UserScript==

if ('mediaSession' in navigator) {
  navigator.mediaSession.metadata = new MediaMetadata({});
}

Object.freeze(navigator.mediaSession.metadata);
Object.freeze(navigator.mediaSession);
```

and I noticed that whatever is generating this bad Media Session API implementation in Chromium source, this can't handle the ```artist``` field in metadata object. I'm not using player-mpris-tail and, given that, idk the code functioning, but for ```player-mpris-simple``` I just added a checking step for length of ```$(playerctl metadata artist)```. With this workaround and ViolentMonkey, I can now filter which domains will be detected or not (at least by the module).
