### ISSUE TITLE
player-mpris-tail compatibility with Tauon Music Box

### ISSUE THREAD

**Issue by Taiko2k** [polybar/polybar-scripts#188]
Using player-mpris-tail with my player Tauon Music Box does not seem to function when player-mpris-tail has already started, but does when reloading. Ref issue https://github.com/Taiko2k/TauonMusicBox/issues/187

This ***does*** seem to function correctly with other MPRIS servers, though I've not had this issue with other MPRIS clients.

My server implementation is here. https://github.com/Taiko2k/TauonMusicBox/blob/master/t_modules/t_dbus.py. Could someone please take a look and see if I'm doing something wrong here? Or is this an issue with player-mpris-tail?

**Comment by x70b1** [comment]
Well, we have some issues open. They all relate to the script `player-mpris-tail`. So it's quite possible that the problem is the script.

The script was contributed by the community, it is from @Cybolic. So I can't say much about it, because I never looked deeper into it. We can only leave this issue open for now, maybe someday there will be someone who wants to solve these problems.

**Comment by Cybolic** [comment]
I can confirm that this is a bug/missing feature in player-mpris-tail.py.
The dbus list is only gone through on init and only clients that generate a `NameOwnerChanged` signal are picked up after that.
I'm not sure exactly which event to listen to in order to detect a new client that doesn't trigger `NameOwnerChanged`, but I'll take a look at it within the next 24 hours.
