### ISSUE TITLE
updates-arch, updates-arch-combined: Why use pacman-contrib?

### ISSUE THREAD

**Issue by OscarAblinger** [polybar/polybar-scripts#196]
As far as I could see, `pacman-contrib` is only used for `checkupdates`.

I'm not familiar with it, so I didn't create a PR, but simply using `pacman -Qu | wc -l` seems to work for me without the added dependency.

Is there a reason for the requirement? Or is it just outdated?

**Comment by x70b1** [comment]
`pacman -Qu | wc -l` asks you local package database for updates. You need to use also `pacman -Sy` for syncing the database. Otherwise you would never see the latest updates, because your local database didn't know it. This means you could use  `pacman -Sy >> /dev/null && pacman -Qu | wc -l` but it would also touch your local database. But sometimes you don't want this.

From [pacman-contrib.git](https://git.archlinux.org/pacman-contrib.git/about/):
> checkupdates - print a list of pending updates without touching the system sync databases (for safety on rolling release distributions).

`checkupdates` use your local database and the repository versions to get the list of updates.

Also `checkupdates` needs no root permission.

This means `checkupdates` is still the best way to check for updates from official sources.
